#!/usr/bin/expect -f
set timeout -1
spawn scp -o StrictHostKeyChecking=no /Users/mwarabu/Development/Projects/React/OUK-Wesites/MainWebsite/backend/restore_menus.ts /Users/mwarabu/Development/Projects/React/OUK-Wesites/MainWebsite/menus.json bentito@197.136.12.53:/home/bentito/ouk-website/backend/
expect {
    "*?assword:*" { send "5o5uJ=gux\r"; exp_continue }
    eof
}
spawn ssh -o StrictHostKeyChecking=no bentito@197.136.12.53 "bash -l -c '
set -e
cd /home/bentito/ouk-website/backend
npx ts-node restore_menus.ts
'"
expect {
    "*?assword:*" { send "5o5uJ=gux\r"; exp_continue }
    eof
}
